build: false

environment:    
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
          PYTHON: "C:\\Python38-x64"

install:
  - set PATH=%PYTHON%;%PYTHON%/Scripts/;%PATH%
  - pip.exe install conan
  - conan profile detect

test_script:
  # Get omniORB dependency
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/softwareschneiderei/conan-omniorb/artifacts/omniorb_conan_cache.tgz'
  - conan cache restore omniorb_conan_cache.tgz
  # Add tango-idl dependency
  - conan export tango-idl
  # Build cpptango
  - conan create . -build=missing
  - conan cache save cpptango/* --file cpptango_conan_cache.tgz

artifacts:
  - path: cpptango_conan_cache.tgz
    name: cppTango conan cache
